map_race = {'Afghanistan':'White', #'Middle Eastern', 
            'African':'Black',#'Black or African American', 
            'African American':'Black',#'Black or African American',
            'Alaska Native':'Other',#'American or Alaska Native',
            'Alaska Native or American Indian or Indigenous: Not Listed':'Other',#'American or Alaska Native',
            'American Indian':'Other',#'American or Alaska Native', 
            'American Indian or Alaska Native':'Other',#'American or Alaska Native',
            'Arab':'White', #'Middle Eastern',
            'Armenian':'White', #'Middle Eastern', 
            'Asian':'Asian', 
            'Asian: Asian Indian':'Asian', #'South Asian',
            'Asian: Chinese':'Asian', #'East Asian', 
            'Asian: Filipino':'Asian', #'South Asian',
            'Asian: Indonesian':'Asian', #'South Asian',
            'Asian: Japanese':'Asian', #'East Asian', 
            'Asian: Korean':'Asian', #'East Asian', 
            'Asian: Not Listed':'Asian',
            'Asian: Other':'Asian',
            'Asian: Pakistani':'Asian', #'South Asian',
            'Asian: Taiwanese':'Asian', #'East Asian', 
            'Asian: Thai':'Asian', #'South Asian',
            'Asian: Vietnamese':'Asian', #'South Asian',
            'Assyrian':'White', #'Middle Eastern', 
            'Bangladeshi':'Asian', #'South Asian',
            'Black':'Black',#'Black or African American', 
            'Black or African American: Not Listed':'Black',#'Black or African American', 
            'Black: African American':'Black',#'Black or African American', 
            'Burmese':'Asian', #'South Asian', 
            'Cambodian':'Asian', #'South Asian', 
            'Caribbean/West Indian':'Other',#'Two or more',
            'Chinese':'Asian', #'East Asian', 
            'Choose Not to Answer':'Other',#'None of the above',
            'Declined to Specify':'Other',#'None of the above',
            'Do not identify with Race':'Other',#'None of the above',
            'Egyptian':'White', #''Middle Eastern', 
            'European':'White',
            'Fijian':'Asian', #'South Asian', 
            'Filipino':'Asian', #'South Asian', 
            'Guamanian/Chamorro':'Other',#'Native Hawaiian or Pacific Islander',
            'Haitian':'Black',#'Black or African American',
            'Hmong':'Asian',#'East Asian', 
            'Indian (India)':'Asian',#'South Asian',
            'Indigenous':'Other',#'American or Alaska Native',
            'Indonesian':'Asian',#'South Asian',
            'Iranian':'White', #'Middle Eastern', 
            'Iraqi':'White', #'Middle Eastern', 
            'Israeli':'White', #'Middle Eastern', 
            'Japanese':'Asian',#'East Asian', 
            'Korean':'Asian',#'East Asian',  
            'Lebanese':'White', #'Middle Eastern', 
            'Middle Eastern or North African: Not Listed':'White',# 'Middle Eastern', 
            'Native Hawaiian':'Other',#'Native Hawaiian or Pacific Islander',
            'Native Hawaiian or Other Pacific Islander':'Other',#'Native Hawaiian or Pacific Islander',
            'Not Listed':'Other',#'None of the above',
            'Other Race':'Other',#'None of the above',
            'Pacific Islander: Guamanian or Chamorro':'Other',#'Native Hawaiian or Pacific Islander',
            'Pacific Islander: Native Hawaiian':'Other',#'Native Hawaiian or Pacific Islander',
            'Pacific Islander: Not Listed':'Other',#'Native Hawaiian or Pacific Islander',
            'Pacific Islander: Other':'Other',#'Native Hawaiian or Pacific Islander',
            'Pacific Islander: Samoan':'Other',#'Native Hawaiian or Pacific Islander', 
            'Pakistani':'Asian',#''South Asian',
            'Palestinian':'White', #'Middle Eastern', 
            'Samoan/American Samoan':'Other',#'Native Hawaiian or Pacific Islander', 
            'Sri Lankan':'Asian',#'South Asian',
            'Syrian':'White', #'Middle Eastern', 
            'Taiwanese':'Asian',#''East Asian',  
            'Thai':'Asian',#'South Asian',
            'Unknown':'Other',#'None of the above',
            'Vietnamese':'Asian',#''South Asian',
            'White':"White", 
            'White or Caucasian':"White", 
            'White: Not Listed':"White",  
            'nan':'Other'}#"None of the above"}

map_ethnicity= {'Choose Not to Answer':'Unknown',
                'Cuban':'Hispanic',
                'Hispanic or Latino':'Hispanic',
                'Hispanic/Spanish origin Other':'Hispanic',
                'Mexican, Mexican American, Chicano/a':'Hispanic',
                'Not Hispanic or Latino':'Non-Hispanic',
                'Puerto Rican':'Hispanic',
                'Unknown':'Unknown',
                'nan':'Unknown'}